package tmuxtest

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"strings"
	"sync"
	"testing"

	"github.com/libtmux/libtmux-go/tmux"
)

// TemporaryNamePrefix prefixes names generated by [NewSession] and [NewWindow].
const TemporaryNamePrefix = "libtmux_"

const temporaryNameAttempts = 128

var temporaryNameMu sync.Mutex

// NewSession creates a test-owned [tmux.Session] and registers cleanup against
// its stable ID. An empty [tmux.NewSessionRequest.Name] receives a
// collision-checked temporary name. The request and referenced values are
// copied before tmux is called, and setup failures call [testing.TB.Fatal].
// Cleanup belongs to t rather than ctx and continues to target the session if
// it is renamed.
func NewSession(
	ctx context.Context,
	t testing.TB,
	server tmux.Server,
	request tmux.NewSessionRequest,
) tmux.Session {
	t.Helper()
	request = captureNewSessionRequest(request)
	if request.Name != "" {
		return createTemporarySession(ctx, t, server, request)
	}

	temporaryNameMu.Lock()
	defer temporaryNameMu.Unlock()
	for range temporaryNameAttempts {
		name, err := temporaryName()
		if err != nil {
			t.Fatal(harnessFailure("generate temporary session name", err))
		}
		request.Name = name
		session, err := server.NewSession(ctx, request)
		if errors.Is(err, tmux.ErrSessionExists) {
			continue
		}
		if err != nil {
			t.Fatal(harnessFailure("create temporary session", err))
		}
		registerSessionCleanup(t, server, session.ID())
		return session
	}
	t.Fatalf("tmuxtest: could not allocate a unique temporary session name")
	return tmux.Session{}
}

// NewWindow creates a test-owned [tmux.Window] and registers cleanup against
// its stable ID. A nil [tmux.NewWindowRequest.Name] receives a collision-checked
// temporary name; an empty non-nil name remains explicit. The request and
// referenced values are copied before tmux is called, and setup failures call
// [testing.TB.Fatal]. Cleanup belongs to t rather than ctx and follows the
// window if it is moved.
func NewWindow(
	ctx context.Context,
	t testing.TB,
	session tmux.Session,
	request tmux.NewWindowRequest,
) tmux.Window {
	t.Helper()
	request = captureNewWindowRequest(request)
	if request.Name != nil {
		return createTemporaryWindow(ctx, t, session, request)
	}

	temporaryNameMu.Lock()
	defer temporaryNameMu.Unlock()
	for range temporaryNameAttempts {
		name, err := temporaryName()
		if err != nil {
			t.Fatal(harnessFailure("generate temporary window name", err))
		}
		exists, err := sessionHasWindowName(ctx, session, name)
		if err != nil {
			t.Fatal(harnessFailure("check temporary window name", err))
		}
		if exists {
			continue
		}
		request.Name = &name
		return createTemporaryWindow(ctx, t, session, request)
	}
	t.Fatalf("tmuxtest: could not allocate a unique temporary window name")
	return tmux.Window{}
}

func createTemporarySession(
	ctx context.Context,
	t testing.TB,
	server tmux.Server,
	request tmux.NewSessionRequest,
) tmux.Session {
	t.Helper()
	session, err := server.NewSession(ctx, request)
	if err != nil {
		t.Fatal(harnessFailure("create temporary session", err))
	}
	registerSessionCleanup(t, server, session.ID())
	return session
}

func createTemporaryWindow(
	ctx context.Context,
	t testing.TB,
	session tmux.Session,
	request tmux.NewWindowRequest,
) tmux.Window {
	t.Helper()
	window, err := session.NewWindow(ctx, request)
	if err != nil {
		t.Fatal(harnessFailure("create temporary window", err))
	}
	registerWindowCleanup(t, session.Server(), window.ID())
	return window
}

func registerSessionCleanup(t testing.TB, server tmux.Server, id tmux.SessionID) {
	t.Helper()
	t.Cleanup(func() {
		result := runCleanupCommand(server, "kill-session", "-t", id.String())
		if err := temporaryResourceCleanupFailure("session", result); err != nil {
			t.Error(harnessFailure("cleanup temporary session", err))
		}
	})
}

func registerWindowCleanup(t testing.TB, server tmux.Server, id tmux.WindowID) {
	t.Helper()
	t.Cleanup(func() {
		result := runCleanupCommand(server, "kill-window", "-t", id.String())
		if err := temporaryResourceCleanupFailure("window", result); err != nil {
			t.Error(harnessFailure("cleanup temporary window", err))
		}
	})
}

func temporaryResourceCleanupFailure(kind string, result tmux.CommandResult) error {
	if result.ExitCode == 0 && len(result.Stderr) == 0 {
		return nil
	}
	if serverUnavailable(result) || temporaryResourceMissing(kind, result) {
		return nil
	}
	if result.ExitCode == 0 {
		return harnessFailure("kill-"+kind, tmux.ErrCommand)
	}
	return commandFailure("kill-"+kind, result)
}

func temporaryResourceMissing(kind string, result tmux.CommandResult) bool {
	if result.ExitCode == 0 || len(result.Stdout) != 0 {
		return false
	}
	prefix := "can't find " + kind
	for _, line := range result.Stderr {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	return false
}

func temporaryName() (string, error) {
	var random [4]byte
	if _, err := rand.Read(random[:]); err != nil {
		return "", err
	}
	return TemporaryNamePrefix + hex.EncodeToString(random[:]), nil
}

func sessionHasWindowName(
	ctx context.Context,
	session tmux.Session,
	name string,
) (bool, error) {
	windows, err := session.Server().Windows(ctx)
	if err != nil {
		return false, err
	}
	for _, window := range windows {
		windowName, ok := window.Name()
		if window.SessionID() == session.ID() && ok && windowName == name {
			return true, nil
		}
	}
	return false, nil
}

func captureNewSessionRequest(request tmux.NewSessionRequest) tmux.NewSessionRequest {
	request.Environment = copyStringMap(request.Environment)
	return request
}

func captureNewWindowRequest(request tmux.NewWindowRequest) tmux.NewWindowRequest {
	request.Name = copyString(request.Name)
	request.Index = copyInt(request.Index)
	request.Environment = copyStringMap(request.Environment)
	return request
}

func copyInt(value *int) *int {
	if value == nil {
		return nil
	}
	result := *value
	return &result
}

func copyString(value *string) *string {
	if value == nil {
		return nil
	}
	result := *value
	return &result
}

func copyStringMap(value map[string]string) map[string]string {
	if value == nil {
		return nil
	}
	result := make(map[string]string, len(value))
	for key, item := range value {
		result[key] = item
	}
	return result
}
